# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b948abba53fcedf59c2edded930f5b2c8cf08f423f5d726bf9541f1ef133efa30d9bc44aa4baca46266ee0eebde4b867c8fab9d0a4a5e821c9c1fe2e3b28a2

test:
  secret_key_base: 1aae83194a0dfe9305d4f1486b5f1162cefcf1a4285c6fbbcef72c27811044e08a4871cde6f0f3785ad342efc371dcc6fd0b778fbd93ebea4a221f06396b3746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
